name: ci-pipeline
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"

      - name: Install poetry
        run: |
          python -m pip install --upgrade poetry
      - id: cache-poetry
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          poetry install
      - name: Run tests
        run: |
          poetry run pytest
